-- Generated by the database client, not guaranteed complete.
CREATE TABLE transferencias(
    "id" SERIAL NOT NULL,
    "emisor" integer,
    "receptor" integer,
    "monto" double precision,
    "fecha" timestamp without time zone,
    PRIMARY KEY(id),
    CONSTRAINT transferencias_emisor_fkey FOREIGN key("emisor") REFERENCES usuarios("id"),CONSTRAINT transferencias_receptor_fkey FOREIGN key("receptor") REFERENCES usuarios("id")
);